H-uru/dirtsand

README
db/dbinit.sql
db/functions.sql

This pull request removes the hardwired "dirtsand" database name and user from the DB scripts. The database is now inferred from the call to `psql`. The readme has been updated to facilitate this change. The benefit here is that it is now easier to run multiple shards on the same machine (production and testing can be separate).

Decouple "dirtsand" from database files

---

GameServ/GameHost.cpp

I noticed several issues with SDL broadcasts when testing my reimplementation of heek. It appeared that in some cases variables were being dropped from the client's SDL. After a bit of code reading, it appears that Plasma expects for the entire SDL blob to come down as a bcast from the server.

BCast Full SDL State

---

AuthServ/AuthClient.h
AuthServ/AuthDaemon.cpp
AuthServ/AuthServer.cpp
GameServ/GameHost.cpp
GameServ/GameServer.cpp
GameServ/GameServer_Private.h
NetIO/CryptIO.cpp
NetIO/CryptIO.h
NetIO/MsgChannel.cpp
NetIO/MsgChannel.h
NetIO/SockIO.cpp
NetIO/SockIO.h
settings.h
streams.h

DS's insistence to send broadcast type messages has had a history of deadlocking the daemon threads. There have been some inferior workarounds that punish players who are on crappy connections (namely, they are disconnected if they cause the daemon thread to block). This is what I consider the best fix for the situation.
Auth and game clients now have another `DS::MsgChannel` for srv2cli broadcasts. MsgChannel's semaphore was changed to an eventfd, which we use poll the socket and eventfd for client and server communication, respectively. The downside is that broadcast messages are now required to be allocated on the heap and refcounted. The plus side is that clients are not punished for being a little slow to handle messages, which is fairly important in cases with lots of messages …

Move all sending operations to client threads

---

GameServ/GameHost.cpp
SDL/SdlParser.cpp

This pull request introduces changes needed to initialize Age SDL for ages that previously did not have an SDL descriptor. It also adds support for ages that have dashes in their filenames, such as GuildPub-Messengers.

Null AgeSDL Fixes

---

NetIO/MsgChannel.cpp

This applies a hack bandaid to crashes that occur when closing an eventfd yields EBADF. I have no idea what's happening there, but if we get EBADF, clearly, we're already closed. The crash can be reproduced easily on master by connecting with the wrong build ID.

Bandage eventfd crashes

---

AuthServ/AuthDaemon.cpp
SDL/DescriptorDb.h

Cyan did so much foolishness with SDL casing that it would just be better to tolerate it. We were having some problems with SpyRoom != spyroom in Gehn.20 :cry:.
Note that Hash and HashI were copied from H-uru/Plasma.

SDL Descriptors are now case-insensitive

---

Types/ShaHash.cpp
dsmain.cpp

Dynamically detect available SHA algorithms and assert when one isn't available (fixes compilation but not functionality with current OpenSSL versions that remove SHA0).  This is the DirtSand equivalent to H-uru/libhsplasma#101

Dynamically detect SHA algorithms and switch to EVP APIs.

---

CMakeLists.txt

Versions of string_theory prior to 1.7 would incorrectly use the case-sensitive hash for both `ST::hash` and `ST::hash_i`

Require string_theory 1.7 for ST::hash_i fixes

---

AuthServ/AuthDaemon.cpp

This incorrect error check caused a false failure on player creation.

Fix incorrect error check in `dm_auth_createPlayer`

---

.travis.yml
CMakeLists.txt
Types/ShaHash.cpp

Add hand-rolled SHA-0 implementation to work around its removal in OpenSSL 1.1 without asserting.

Add hand-rolled SHA-0 implementation.

---

NetIO/Lobby.cpp
NetIO/SockIO.cpp
NetIO/Status.cpp
dsmain.cpp
errors.h
settings.cpp
settings.h

- Automatically detect dirtsand.ini if it's in a "usual" location.
- Don't crash if something else is listening on port 8080 -- just display a warning and move on.
- General cleanup.

Improve dirtsand startup

---

AuthServ/AuthDaemon.cpp
AuthServ/AuthManifest.cpp
AuthServ/AuthVault.cpp
AuthServ/VaultTypes.cpp
CMakeLists.txt
FileServ/FileManifest.cpp
GameServ/GameServer.cpp
NetIO/CryptIO.cpp
NetIO/Status.cpp
PlasMOUL/AgeLinkStruct.h
SDL/StateInfo.cpp
settings.cpp
streams.cpp

* Fixes compatibility with string_theory master (to be 3.0)
* Removes an unnecessary extra allocation/copy in SafeString writes.

Require string_theory 2.0.

---

AuthServ/AuthDaemon.cpp

This fixes an issue in which an error was sent to the client but the auth server continued under the assumption of success.

Fix an error-case fall through

---

AuthServ/AuthVault.cpp

This oversight in the extern declaration of the `s_globalStates` map apparently caused the age filenames to stored in the map with case sensitive hashes. The case insensitive hash lookup in the AuthServ then failed, causing a null State to be given to the GameHost, resulting in a crash on merging a null State.
This should fix #122.

Fix segfault on GameHost start.

---

AuthServ/AuthClient.h
NetIO/MsgChannel.cpp
NetIO/MsgChannel.h

In pull request #126, `DS::MsgChannel` was changed to lazy-initialize the eventfd. This is sensible because, in many places, DS uses temporary clients that do not need all MsgChannels available. Unfortunately, this introduces a potential race condition. This can be observed primarily in the `dm_game_join` handler, which pushes an `e_UpdateAgeSrv` message to the AuthDaemon. The auth server responds so quickly that there is a race between the GameHost calling `m_channel.getMessage()` and the AuthHost calling `m_channel.putMessage` that the two end up operating on different eventfds, causing the GameHost to hang forever. Anyone linking to that age from then on is permanently stuck in the spinning book age. Most other situations are not particularly vulnerable to this race condition because …

Fix race condition in `DS::MsgChannel`.

---

SDL/DescriptorDb.h
SDL/SdlParser.cpp
SDL/StateInfo.cpp
SDL/StateInfo.h
Types/UnifiedTime.h

This addresses both issues identified in #148.

Properly initialize and check SDL descriptor structures when parsing.

---

PlasMOUL/Avatar/AvBrainGeneric.cpp
PlasMOUL/Avatar/AvTask.cpp
PlasMOUL/Avatar/AvTask.h
PlasMOUL/Avatar/CoopCoordinator.cpp
PlasMOUL/Messages/AvTaskMsg.h
PlasMOUL/Messages/AvatarMsg.cpp
PlasMOUL/Messages/AvatarMsg.h
PlasMOUL/Messages/CreatableList.cpp
PlasMOUL/Messages/LoadAvatarMsg.cpp
PlasMOUL/Messages/LoadAvatarMsg.h
PlasMOUL/Messages/LoadCloneMsg.cpp
PlasMOUL/Messages/LoadCloneMsg.h
PlasMOUL/Messages/MessageWithCallbacks.cpp
PlasMOUL/NetMessages/NetMsgGameMessage.cpp
PlasMOUL/NetMessages/NetMsgGameMessage.h
PlasMOUL/creatable.h
SDL/StateInfo.cpp

GCC very kindly inlines `safe_unref` for us, which causes the `if (pcre)` statement to evaluate to `if (this)`, which is optimized away.

Fix crash when reading NetGameMessages in Release.

---

static_ages.ini

Update static_ages.ini to current.
These UUIDs were generated by me for these fan Ages. The general rule is to use a UUIDv5 of the Age's filename with the namespace being the client UUID. Unfortunately, 0b4f5ad9-d93d-52e3-83e4-9364c2149ae4 was generated before I knew the actual filename of ChisoPreniv (the UUID was generated with Chiso).

Add new static fan Ages.

---

NetIO/Status.cpp

JavaScript allows single quotes, but JSON doesn't.

Fix /status to return actual valid JSON

---

PlasMOUL/Messages/EventData.cpp

This crashes the server when visiting the Neighborhood with a player whose name contains non-ASCII characters.... Although, in my experience it has caused a weird game host deadlock instead of a full-blown crash. All hail address sanitizer for helping me find this.
A more general question, though... It looks like in Plasma safe strings are now assumed to be UTF-8 by default while DS is assuming latin_1 by default. I think, in years past, DS's assumption matched Plasma's, but that seems to no longer be the case. Should we consider switching the default string format to `e_StringUTF8`?

Fix proVariableEvent string reading/writing.

---

AuthServ/AuthVault.cpp

This means there is less communication required with the DB to perform what is really a single operation. Previously, the worst case scenario could result in 200 queries being sent to the DB for one public Age lookup. Now, only one query is sent to the DB server.

Retrive the public Age list in one query.

---

streams.cpp

This crashed the server when outputting UTF-16 strings that contain more than a few non-ASCII characters.

Fix incorrect lengths in `writeSafeString` for non-ASCII strings

---

CMakeLists.txt

Now works again with at least CMake 3.7.2.

Fix compatibility with older CMake versions

---

AuthServ/AuthManifest.cpp
AuthServ/AuthManifest.h
CMakeLists.txt
FileServ/FileManifest.cpp
FileServ/FileManifest.h

Note: Taking a reference from `emplace_back()` requires a bump to C++17.  It's probably time to do that anyway...

Reduce unnecessary heap allocations and copies in manifest code

---

NetIO/CryptIO.cpp

The original client code would only write the trailing nul character when the copied string had a non-zero length.  Furthermore, the DirtSand code could attempt to write the trailing nul outside the buffer, which is dangerous! This fixes both issues by only writing the trailing nul when the strings are non-empty.

Fix a compatibility issue with the Sha0 hashing for usernames and passwords.

---

AuthServ/AuthDaemon.cpp
NetIO/CryptIO.cpp
NetIO/CryptIO.h

1) Fix the conditional for gametap domains to use the same regular expression that the client uses.  It might have otherwise picked the wrong branch for some cases (e.g. "foo@bar" or "me@tld.gametap.com").
2) Actually use `BuggyHashPassword` when creating an account with an email-based username.  Previously, `BuggyHashPassword` wasn't ever used anywhere, and the SHA-1 hash was used unconditionally when adding accounts.

Two fixes for email-based authentication

---

AuthServ/AuthVault.cpp

...  rather than just matching any node that happens to have the right values in `int32_1` and `string64_2`

Check node type when looking for public ages

---

AuthServ/AuthServer_Private.h
SDL/StateInfo.h

A couple of minor fixes:
- Update the ServerCaps enumeration to match what's currently in the client due to GameMgr work. DS still doesn't support the GameMgr, so this is unused.
- Change the SDL variable type numeration to match the client exactly. This is never sent to the client, but it theoretically *could* be due to the client having read/write methods for `plStateDescriptor`.

Minor Auth/SDL Fixes.

---

docker-compose.yml

The previous values would cause the postgres container to restart when, for example, the computer was restarted. The dirtsand container was left unrestarted. We don't want to automatically restart the containers when the computer boots up, I expect, and we definitely want for the containers to have the same restart policy. It seems like the best approach is to restart the containers when they crash only.

Fix dockersand restart directives.

---

AuthServ/AuthServer.cpp
GameServ/GameServer.cpp

Somehow, when repeated connection attempts came in from a single client with a bad build ID, we would hit a segfault where the auth client's broadcast channel would have an invalid message in it. It is unclear how this message got in the channel, but I did notice that `poll()` is returning that the client's socket is `POLLNVAL`. Treating `POLLNVAL` as a regular hangup seems to prevent the problem.

Fix a segfault related to clients connecting with the wrong build ID.

---

GameServ/GameHost.cpp

The client can't actually handle these messages, so they produce "Unknown msg" errors in network.log.

Don't propagate `plNetMsgPagingRoom` to other clients

---

PlasMOUL/Avatar/ArmatureBrain.h
PlasMOUL/Avatar/AvBrainGeneric.cpp
PlasMOUL/Avatar/AvBrainGeneric.h
PlasMOUL/Avatar/AvTask.cpp
PlasMOUL/Avatar/AvTask.h
PlasMOUL/Avatar/CoopCoordinator.cpp
PlasMOUL/Avatar/CoopCoordinator.h
PlasMOUL/Messages/AvTaskMsg.cpp
PlasMOUL/Messages/AvTaskMsg.h
PlasMOUL/Messages/AvatarMsg.cpp
PlasMOUL/Messages/LoadAvatarMsg.cpp
PlasMOUL/Messages/LoadAvatarMsg.h
PlasMOUL/Messages/LoadCloneMsg.cpp
PlasMOUL/Messages/LoadCloneMsg.h

`AvBrainGeneric` can contain arbitrary messages, and so can (indirectly) many avatar-related messages that contain a brain and/or task. This change ensures that such nested messages are checked for net-safety.
H-uru/Plasma#1550 implements similar checks on the receiving end in the client.

Implement `makeSafeForNet` more thoroughly for avatar-related messages

---

dockersand.sh

The original version of Docker Compose was a separate utility, which provided a docker-compose command-line tool.
Docker Compose v2 is a Docker plugin, which is meant to be run as a subcommand of Docker (i.e., `docker compose ...`). In most cases, it provides a `docker-compose` tool for backwards compatibility that forwards to the plugin, but in some cases that tool is either missing or not properly added to the path.
We will therefore try to run `docker-compose`, and if it fails we will try to run `docker compose` and see if that works before exiting with an error. If `docker compose` is supported, we will use that for subsequent commands.

Better edge case handling around Docker Compose v2

---

streams.cpp

As is currently the case for some SDL files in the H'uru/Plasma repo.
This fixes some `[SDL] Unexpected EOF` errors/warnings (?) on startup.

Fix `DS::Stream::readLine` for files without a trailing newline

---

README.md
dockersand.bat

Got a report on discord:
```
PS D:\dirtsand> ./dockersand build
./dockersand : File D:\dirtsand\dockersand.ps1 cannot be loaded because running scripts is disabled on this system.
For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ ./dockersand build
+ ~~~~
+ CategoryInfo          : SecurityError: (:) [], PSSecurityException
+ FullyQualifiedErrorId : UnauthorizedAccess
```
Assuming that `./dockersand` is mapping to `dockersand.bat`, the default policy might be messing with us. Most all resources online suggest using `NoProfile` when using helper scripts to launch PowerShell, so let's do it.

Fix problems related to dockersand.bat

---

AuthServ/AuthServer.cpp
CMakeLists.txt
Dockerfile
bin/docker-entrypoint.sh

Currently, OU clients don't handle the Auth2Cli_ServerCaps message, and that results in the network stream getting into a bad state where the client throws an error and gives us.
This compatibility hack from dgelessus is interpreted as a ServerCaps response by newer clients that understand that message, and as a harmless file download response by older clients which don't.

Optional backwards compatibility with older clients

---

Tests/Test_EncryptedStream.cpp
streams.cpp

Replace fputc with ungetc to fix UB
